specVersion: 1.0.0
name: khala-chainbridge-subql
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Generic index service for Khala network
repository: 'https://github.com/Phala-Network/khala-chainbridge-subql.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d'
  endpoint: 'wss://khala.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/khala-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 2758848
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTreasuryDeposit
          kind: substrate/EventHandler
        - handler: handleMinerSettled
          kind: substrate/EventHandler
